# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: adtekio_adnetworks 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "adtekio_adnetworks"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Gerrit Riessen"]
  s.date = "2016-08-19"
  s.description = "Encapsulate adnetworks and their importers."
  s.email = "gerrit@eccrine.io"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "adtekio_adnetworks.gemspec",
    "lib/adtekio_adnetworks.rb",
    "lib/adtekio_adnetworks/configuration.rb",
    "lib/adtekio_adnetworks/importers.rb",
    "lib/adtekio_adnetworks/importers/cost/adcolony.rb",
    "lib/adtekio_adnetworks/importers/cost/adquant.rb",
    "lib/adtekio_adnetworks/importers/cost/appia.rb",
    "lib/adtekio_adnetworks/importers/cost/applifier.rb",
    "lib/adtekio_adnetworks/importers/cost/applift.rb",
    "lib/adtekio_adnetworks/importers/cost/applovin.rb",
    "lib/adtekio_adnetworks/importers/cost/bidmotion.rb",
    "lib/adtekio_adnetworks/importers/cost/chartboost.rb",
    "lib/adtekio_adnetworks/importers/cost/crossinstall.rb",
    "lib/adtekio_adnetworks/importers/cost/facebook.rb",
    "lib/adtekio_adnetworks/importers/cost/fractionalmedia.rb",
    "lib/adtekio_adnetworks/importers/cost/fyber.rb",
    "lib/adtekio_adnetworks/importers/cost/gamegenetics.rb",
    "lib/adtekio_adnetworks/importers/cost/glispa.rb",
    "lib/adtekio_adnetworks/importers/cost/googleadwords.rb",
    "lib/adtekio_adnetworks/importers/cost/jampp.rb",
    "lib/adtekio_adnetworks/importers/cost/leadbolt.rb",
    "lib/adtekio_adnetworks/importers/cost/lifestreet.rb",
    "lib/adtekio_adnetworks/importers/cost/loopme.rb",
    "lib/adtekio_adnetworks/importers/cost/matomy.rb",
    "lib/adtekio_adnetworks/importers/cost/mdotm.rb",
    "lib/adtekio_adnetworks/importers/cost/mmg.rb",
    "lib/adtekio_adnetworks/importers/cost/mnectar.rb",
    "lib/adtekio_adnetworks/importers/cost/moboqo.rb",
    "lib/adtekio_adnetworks/importers/cost/mobpartner.rb",
    "lib/adtekio_adnetworks/importers/cost/nanigans.rb",
    "lib/adtekio_adnetworks/importers/cost/revmob.rb",
    "lib/adtekio_adnetworks/importers/cost/rtbmob.rb",
    "lib/adtekio_adnetworks/importers/cost/startapp.rb",
    "lib/adtekio_adnetworks/importers/cost/supersonic.rb",
    "lib/adtekio_adnetworks/importers/cost/tapjoy.rb",
    "lib/adtekio_adnetworks/importers/cost/tokenads.rb",
    "lib/adtekio_adnetworks/importers/cost/unilead.rb",
    "lib/adtekio_adnetworks/importers/cost/vungle.rb",
    "lib/adtekio_adnetworks/importers/cost_import.rb",
    "lib/adtekio_adnetworks/importers/revenue/adcolony.rb",
    "lib/adtekio_adnetworks/importers/revenue/applifier.rb",
    "lib/adtekio_adnetworks/importers/revenue/applovin.rb",
    "lib/adtekio_adnetworks/importers/revenue/chartboost.rb",
    "lib/adtekio_adnetworks/importers/revenue/flurry.rb",
    "lib/adtekio_adnetworks/importers/revenue/fyber.rb",
    "lib/adtekio_adnetworks/importers/revenue/hypr_mx.rb",
    "lib/adtekio_adnetworks/importers/revenue/lifestreet.rb",
    "lib/adtekio_adnetworks/importers/revenue/mdotm.rb",
    "lib/adtekio_adnetworks/importers/revenue/mopub.rb",
    "lib/adtekio_adnetworks/importers/revenue/nexage.rb",
    "lib/adtekio_adnetworks/importers/revenue/supersonic.rb",
    "lib/adtekio_adnetworks/importers/revenue/tapsense.rb",
    "lib/adtekio_adnetworks/importers/revenue/trialpay.rb",
    "lib/adtekio_adnetworks/importers/revenue/vungle.rb",
    "lib/adtekio_adnetworks/importers/revenue_import.rb"
  ]
  s.homepage = "https://github.com/adtekio/adnetworks.git"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Encapsulate adnetworks and their importers."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-http-persistent>, [">= 0"])
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<oauth2>, [">= 0"])
      s.add_runtime_dependency(%q<mechanize>, [">= 0"])
      s.add_runtime_dependency(%q<google-adwords-api>, [">= 0"])
      s.add_runtime_dependency(%q<google-api-client>, [">= 0"])
      s.add_runtime_dependency(%q<curb>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<pry-doc>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
    else
      s.add_dependency(%q<net-http-persistent>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<oauth2>, [">= 0"])
      s.add_dependency(%q<mechanize>, [">= 0"])
      s.add_dependency(%q<google-adwords-api>, [">= 0"])
      s.add_dependency(%q<google-api-client>, [">= 0"])
      s.add_dependency(%q<curb>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<pry-doc>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
    end
  else
    s.add_dependency(%q<net-http-persistent>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<oauth2>, [">= 0"])
    s.add_dependency(%q<mechanize>, [">= 0"])
    s.add_dependency(%q<google-adwords-api>, [">= 0"])
    s.add_dependency(%q<google-api-client>, [">= 0"])
    s.add_dependency(%q<curb>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<pry-doc>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
  end
end

